trajectory_execution:
  allowed_execution_duration_scaling: 1.2
  allowed_goal_duration_margin: 0.5
  allowed_start_tolerance: 0.0

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - brtirus0707a_controller

  brtirus0707a_controller:
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - brtirus0707a_joint_1
      - brtirus0707a_joint_2
      - brtirus0707a_joint_3
      - brtirus0707a_joint_4
      - brtirus0707a_joint_5
      - brtirus0707a_joint_6
